services:
  mongo:
    image: mongo:latest
    container_name: "trino_llm_agent"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "trino_llm_agent"
      MONGO_INITDB_ROOT_PASSWORD: "tmp" #TODO: use a secret
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

volumes:
  mongo_data:

networks:
  local:
    driver: bridge
